apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: servb
  namespace: my-apps
spec:
  awsName: servb-virtual-node
  podSelector:
    matchLabels:
      app: servb
  listeners:
    - portMapping:
        port: 80
        protocol: http
  serviceDiscovery:
    dns:
      hostname: servb.my-apps.svc.cluster.local
  logging:
    accessLog:
      file:
        path: "/dev/stdout"   # find this in /aws/containerinsights/Cluster_Name/application log group. must be routing eks logs to cloudwatch logs using e.g. fluent-bit
      
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: servb
  namespace: my-apps
spec:
  awsName: servb.my-apps.svc.cluster.local
  provider:
    virtualNode:
      virtualNodeRef:
        name: servb