apiVersion: v1
kind: Service
metadata:
  name: servb
  namespace: my-apps
  labels:
    app: servb
spec:
  selector:
    app: servb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: servb
  namespace: my-apps
  labels:
    app: servb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servb
  template:
    metadata:
      labels:
        app: servb
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.0
        ports:
        - containerPort: 80